### ISSUE TITLE
Enable playback to gather all errors without instantly breaking

### ISSUE THREAD

**Issue by spamsch** [perfact/zodbsync#1]
Currently playback will break if it encounters an error. For better usability it should be possible to collect all errors and then show them at the end.

**Comment by spamsch** [comment]
With https://github.com/perfact/zodbsync/pull/2 I added a first step by ensuring that --skip-errors is propagated properly. I also moved logging level for standard upload to DEBUG so that errors are more apparent.

**Comment by viktordick** [comment]
Should be fixed with #2
