### ISSUE TITLE
Python Scripts no longer recorded in Zope 4

### ISSUE THREAD

**Issue by viktordick** [perfact/zodbsync#10]
After using perfact-zopeplayback to successfully load a recorded Zope2.13-Data.FS (which was first transformed using 2to3 and gocept.template_rewrite) into Zope4b9 and re-recording it, all Python Scripts have lost their sources and only __meta__-files remain. This has to be investigated.

**Comment by gandie** [comment]
Can not reproduce using current master of zodbsync and Zope4b10 release. Python script sources came out totally fine. I used a very small Data.fs created in Zope4 containing only a few python scripts for testing.

**Comment by viktordick** [comment]
Could not reproduce anymore either, closing.
