### ISSUE TITLE
Publish project on Pypi?

### ISSUE THREAD

**Issue by sweh** [perfact/zodbsync#120]
We use zodbsync in our legacy application and have already contributed one or two pull requests via gocept in the last few weeks. So that we don't have to check out zodbsync on every VM running our application, it would be fantastic if zodbsync was published on the Pypi.

What speaks against it in your opinion?

**Comment by viktordick** [comment]
Hi,
there is no reason against it except that I have never done it until now and need to read up on how to do it ;)
Until now we simply used `git+https://...` lines in our `requirements.txt`, but I will check up on how to publish on pypi at some point in the next 2-3 weeks.

**Comment by viktordick** [comment]
If you say `legacy application` - are we talking about still supporting Python 2? Just curious if the package should also contain an older release (we just dropped support for Python 2, there is not even a release out yet).

**Comment by sweh** [comment]
We are currently porting it to Python 3, so we can get over a non-existent Python 2 release. But a Python 3 release would be very nice for the future.

**Comment by viktordick** [comment]
The currently released version 22.2.5 is now found on pypi under `perfact-zodbsync`.

Although I will have to release a follow-up version because the README still tells to install from github...

**Comment by sweh** [comment]
Thank you very much!
