### ISSUE TITLE
after installation and running with the command "zodbsync record" this error appears

### ISSUE THREAD

**Issue by mtessari** [perfact/zodbsync#38]
after installation and running with the command "zodbsync record" this error appears:

]$ zodbsync record
Traceback (most recent call last):
  File "/app/zope45-draft/bin/zodbsync", line 6, in <module>
    perfact.zodbsync.main.run()
  File "/app/zope45-draft/lib64/python3.6/site-packages/perfact/zodbsync/main.py", line 29, in run
    create_runner().run()
  File "/app/zope45-draft/lib64/python3.6/site-packages/perfact/zodbsync/main.py", line 24, in create_runner
    return SubCommand.create(argv=argv, subcommands=commands)
  File "/app/zope45-draft/lib64/python3.6/site-packages/perfact/zodbsync/subcommand.py", line 38, in create
    return args.runner(args=args)
  File "/app/zope45-draft/lib64/python3.6/site-packages/perfact/zodbsync/subcommand.py", line 73, in __init__
    self.sync = ZODBSync(conffile=args.config, logger=logger)
  File "/app/zope45-draft/lib64/python3.6/site-packages/perfact/zodbsync/zodbsync.py", line 238, in __init__
    'config', conffile).load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/etc/perfact/modsync/zodb.py'

Where can I found zodb.py ?
thancks

**Comment by viktordick** [comment]
Sorry for the bad documentation in this regard.
The top-level file `config.py` is an example configuration for this. You can pass another file name using the parameter `-c`. The default location in `/etc/perfact` has this value because we internally package this in a Debian package together with other stuff (like a full Zope installation inside a virtual environment) and provide our config file there.

**Comment by viktordick** [comment]
On a second glance, the `README` actually mentions to use `config.py` as a starting point. However, it does not mention to pass it using the `-c` parameter.

**Comment by mtessari** [comment]
Thank you very much for your answer, I try it but finally I had to change
the zodbsync.py source code with this :

line 243 #         config.base_dir
        self.base_dir =
'/app/instance-zope45-draft/prima_prova/zodbsync_dir'

and

line 259 #             configure_wsgi(config.wsgi_conf_path)

configure_wsgi('/app/instance-zope45-draft/prima_prova/etc/zope.conf')

In this way using the command
(zope45-draft) [username@localhost zope45-draft]$ zodbsync record
seams to running but at the and this is the result :

$ zodbsync record
Duplicate Product name: After loading Product 'BTreeFolder2' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'ExternalMethod' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'Five' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'GenericSetup' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'OFSP' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'PageTemplates' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'PluggableAuthService' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'PluginIndexes' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'PluginRegistry' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'PythonScripts' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'Sessions' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'SiteAccess' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'SiteErrorLog' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'StandardCacheManagers' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'Transience' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'ZCTextIndex' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'ZCatalog' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'ZPsycopgDA' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'ZSQLMethods' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'BTreeFolder2' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'ExternalMethod' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'Five' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'GenericSetup' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'OFSP' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'PageTemplates' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'PluggableAuthService' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'PluginIndexes' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'PluginRegistry' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'PythonScripts' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'Sessions' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'SiteAccess' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'SiteErrorLog' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'StandardCacheManagers' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'Transience' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'ZCTextIndex' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'ZCatalog' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'ZPsycopgDA' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.
Duplicate Product name: After loading Product 'ZSQLMethods' from
'/app/zope45-draft/lib64/python3.6/site-packages/Products', I skipped the
one in '/app/zope45-draft/lib/python3.6/site-packages/Products'.

and in the destination directory
/app/instance-zope45-draft/prima_prova/zodbsync_dir
I found only this empty file ".zodbsync.lock "

Please have you any idea ?


Il giorno ven 7 ago 2020 alle ore 12:33 Viktor Dick <
notifications@github.com> ha scritto:

**Comment by mtessari** [comment]
Sorry my OS is a centOS

Il giorno ven 7 ago 2020 alle ore 14:57 Matteo Tessari <
tessari.matteo1977@gmail.com> ha scritto:

**Comment by viktordick** [comment]
You have to provide a path to `zodbsync record`, for example `zodbsync record /` to record the complete everything that is supported.

You should be able to change the paths in the config and provide the config using `-c config.py` (I think this parameter must be passed before giving the subcommand like `record`, so use something like `zodbsync -c config.py record /`.

**Comment by viktordick** [comment]
@mtessari Are your questions answered? Can this issue be closed?

**Comment by mtessari** [comment]
Hi for the moment yes, anyway the -c parameter under CentOS is not working,
I had put the parameter in the source code, and with the parameter "/" at
the end of the command the tool export in the correct folder.
Anyway I exported and imported the content of the zope4.5 version
successfully.

Unfortunately I have stopped my updating work from zope2.12 to zope4.5, I
think that next week I'll go ahead with this activity,  next step is
install the tool in a zope 2.12 istance to export source code and then
import this in a zope4.5 version.

I'll let you know how it works in zope2.12.

Thank you very very much for the support and the tips.

Il giorno mer 12 ago 2020 alle ore 19:54 Viktor Dick <
notifications@github.com> ha scritto:

**Comment by viktordick** [comment]
Hm maybe you appended the `-c` argument behind the subcommand (`record`)? It is a generic argument independent of the subcommand, so it has to be supplied before it, like

    zodbsync -c config.py record /

Anyway, assuming you also want to switch to Python 3 when switching to Zope 4, you might want to check out [`gocept.template_rewrite`](https://github.com/gocept/gocept.template_rewrite). It can be used to rewrite Python expressions inside DTML and Page Templates using `2to3` after they have been recorded using `zodbsync`.
